.PHONY: default test test-cloudbuild

default:

# NOTE: Cloud Build doesn't use this Makefile as it needs to run the individual
# up/run/down steps on different containers. This is just a stub for consistency
# with the other tools.
# When developing locally it's faster when repeatedly running tests to
# use once "./test.sh up", then use "./test.sh run".
test:
	./test.sh
