# Start Postgres using docker compose so that we can wait until the container
# is healthy.
name: knfsd-fsidd-postgres
services:
  postgres:
    image: postgres:14.7-alpine3.17
    healthcheck:
      test: "pg_isready --host=127.0.0.1 --username=\"$$POSTGRES_USER\" --dbname=\"$$POSTGRES_DB\""
      interval: 5s
      timeout: 15s
      retries: 6
      start_period: 5m
    ports:
      # bind the container port 5432 to a random local port
      # only expose this port to localhost
      - target: 5432
        host_ip: 127.0.0.1
    environment:
      POSTGRES_PASSWORD: fsid-test
      POSTGRES_USER: fsidd
      POSTGRES_DB: fsids
